/**
 * Jira Card Generator
 *
 * Converts clusters into Jira-compatible JSON for bulk import.
 */

export interface ClusterData {
  id: string;
  name: string;
  files: string[];
  totalLines?: number;
  conflictCount?: number;
  description?: string;
}

export interface JiraIssue {
  fields: {
    project: { key: string };
    summary: string;
    description: string;
    issuetype: { name: string };
    labels?: string[];
    priority?: { name: string };
    customfield_10000?: any; // Story points - field ID varies by Jira instance
  };
}

export interface JiraBulkImport {
  issueUpdates: JiraIssue[];
}

/**
 * Generate a Jira issue from a cluster
 */
export function clusterToJiraIssue(
  cluster: ClusterData,
  projectKey: string,
  issueType: string = 'Task'
): JiraIssue {
  const fileList = cluster.files
    .map(f => `* ${f}`)
    .join('\n');

  const description = `h2. Overview
${cluster.description || `Resolve conflicts in the ${cluster.name} cluster to enable migration to shared codebase.`}

h2. Files in this cluster (${cluster.files.length})
{noformat}
${fileList}
{noformat}

h2. Acceptance Criteria
* All files in this cluster have been merged/resolved
* Both restaurant and retail builds pass
* No regressions in affected functionality

h2. Notes
* Generated by Branch Consolidator
* Cluster ID: ${cluster.id}
${cluster.totalLines ? `* Estimated lines changed: ${cluster.totalLines}` : ''}
`;

  return {
    fields: {
      project: { key: projectKey },
      summary: `[WebPOS Consolidation] ${cluster.name}`,
      description: description,
      issuetype: { name: issueType },
      labels: ['webpos-consolidation', 'auto-generated'],
    }
  };
}

/**
 * Generate bulk import JSON from clusters
 */
export function generateBulkImport(
  clusters: ClusterData[],
  projectKey: string,
  issueType: string = 'Task'
): JiraBulkImport {
  return {
    issueUpdates: clusters.map(c => clusterToJiraIssue(c, projectKey, issueType))
  };
}

/**
 * Generate individual issue JSON files
 */
export function generateIssueFiles(
  clusters: ClusterData[],
  projectKey: string,
  issueType: string = 'Task'
): { filename: string; content: JiraIssue }[] {
  return clusters.map((cluster, index) => ({
    filename: `jira-issue-${String(index + 1).padStart(3, '0')}-${cluster.id}.json`,
    content: clusterToJiraIssue(cluster, projectKey, issueType)
  }));
}

/**
 * Estimate story points based on cluster size
 */
export function estimateStoryPoints(cluster: ClusterData): number {
  const fileCount = cluster.files.length;
  if (fileCount <= 2) return 1;
  if (fileCount <= 5) return 2;
  if (fileCount <= 10) return 3;
  if (fileCount <= 20) return 5;
  return 8;
}

/**
 * Generate a summary report of all cards
 */
export function generateSummaryReport(clusters: ClusterData[]): string {
  const totalFiles = clusters.reduce((sum, c) => sum + c.files.length, 0);
  const totalPoints = clusters.reduce((sum, c) => sum + estimateStoryPoints(c), 0);

  let report = `# Jira Card Generation Summary\n\n`;
  report += `- Total clusters: ${clusters.length}\n`;
  report += `- Total files covered: ${totalFiles}\n`;
  report += `- Estimated total story points: ${totalPoints}\n\n`;
  report += `## Cards by Size\n\n`;
  report += `| Cluster | Files | Est. Points |\n`;
  report += `|---------|-------|-------------|\n`;

  const sorted = [...clusters].sort((a, b) => b.files.length - a.files.length);
  for (const cluster of sorted) {
    report += `| ${cluster.name} | ${cluster.files.length} | ${estimateStoryPoints(cluster)} |\n`;
  }

  return report;
}
